version: "3.5"

services:
  web:
    build: .
    command: python -u src/app.py
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: "mongo@4.2.0"

networks:
  default:
    name: "network-web"